spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.64.78/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#  mail:
#    host: smtp.qq.com
#    username: 1532328736@qq.com
#    password: xhrnpknoasohiebd
#    default-encoding: utf-8
server:
  port: 10086
